services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-nequi_franquicias
    env_file: 
      - .env
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: ${MYSQL_URL}
      SPRING_R2DBC_USERNAME: ${MYSQL_USER}
      SPRING_R2DBC_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:9.2
    container_name: NequiFranquicias
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_SSL_CIPHER: ${MYSQL_SSL_CIPHER}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
