spring.application.name=franquicias

spring.r2dbc.url=r2dbc:mysql://terraform-20250225025026050700000001.c5u46mwm073h.us-east-1.rds.amazonaws.com:3306/nequi_franquicias
spring.r2dbc.username=admin
spring.r2dbc.password=contrasenamuysegura123

spring.sql.init.platform=mysql
spring.sql.init.mode=always
